# Generated by Django 5.0 on 2024-01-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDigesto', '0002_digesto_fecha_vigencia_digesto_numerodigesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digesto',
            name='numeroDigesto',
            field=models.CharField(max_length=15),
        ),
    ]
