# Generated by Django 5.0 on 2024-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDigesto', '0003_alter_digesto_numerodigesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digesto',
            name='fecha_vigencia',
            field=models.DateField(auto_now_add=True),
        ),
    ]
